# Generated by Django 5.0.2 on 2024-03-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.IntegerField(unique=True)),
                ('faixa_idade', models.CharField(max_length=2)),
                ('sexo', models.CharField(max_length=1)),
                ('estado_civil', models.CharField(max_length=1)),
                ('raca', models.CharField(max_length=1)),
                ('nacionalidade', models.CharField(max_length=1)),
                ('conclusao_status', models.CharField(max_length=1)),
                ('conclusao_ano', models.CharField(max_length=2)),
                ('tipo_escola', models.CharField(max_length=1)),
                ('conclusao_situacao', models.CharField(max_length=1)),
                ('treineiro', models.BooleanField()),
                ('CN', models.DecimalField(decimal_places=2, max_digits=4)),
                ('CH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('LC', models.DecimalField(decimal_places=2, max_digits=4)),
                ('MT', models.DecimalField(decimal_places=2, max_digits=4)),
                ('REDACAO', models.DecimalField(decimal_places=2, max_digits=4)),
                ('MEDIA', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
