# Generated by Django 5.0.2 on 2024-04-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0002_alter_dados_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='CH',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dados',
            name='CN',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dados',
            name='LC',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dados',
            name='MEDIA',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dados',
            name='MT',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dados',
            name='REDACAO',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
